[userinfo]
user = 0

[widefind]
enabled = true
ip = "130.240.74.55"
port = 1883

[fibaro]
enabled = false
ip = "http://130.240.114.44/api/"
user = "unicorn@ltu.se"
password = "Ks2mpH2Al!"

[phue]
enabled = true
ip = "130.240.114.9"


# Explanations here

#WideFind
#if   = ["position"]
#then = ["lamp_x_on/off"]

[rules_0]
if =    ["door_42_open", "position_000_kitchen", "door_42_open", "widefind_1_dörr", "widefind_1_tv-bänk", "widefind_1_icke-dörr", "widefind_1_icke-tv-bänk"]
then =  ["lamp_1_on"   , "lamp_2_on"           , "lamp_3_off"  , "lamp_13_on", "lamp_14_on", "lamp_13_off", "lamp_14_off"]