[userinfo]
user = 0

[widefind]
enabled = false
ip = "130.240.74.55"
port = 1883

[fibaro]
enabled = true
ip = "http://130.240.114.44/api/"
user = "unicorn@ltu.se"
password = "Ks2mpH2Al!"

[phue]
enabled = true
ip = "130.240.114.9"


# -------- EXPLANATIONS --------
#
# INPUT:
#
# Widefind: id is always 000
# Status: kitchen, livingroom (tv-b채nk), hallway
# Example: position_000_kitchen
#
# Fibaro: 42 is front door
# Status: open, closed
# Example: door_42_open
#
# -----------------------------
#
# OUTPUT:
#
# Lamps: 13 is front door, 14 is living room, 15 is kitchen
# Lamp actions: on, off, yellow, purple
# Example: lamp_13_on


# -------- RULES --------

#[rules_0]
#if =    ["door_42_open", "position_000_kitchen", "door_42_open", "position_001_tv-b채nk", "position_001_tv-b채nk", "position_001_tv-b채nk"]
#then =  ["lamp_13_on"  , "lamp_2_on"           , "lamp_3_off"  , "13", "14", "15"]

[rules_0]
if   = ["door_42_open"]
then = ["lamp_14_yellow"]