[userinfo]
user = 1
currentRule = "rules_0"

[simulator]
enabled = true

[widefind]
enabled = false
ip = "130.240.74.55"
port = 1883

[fibaro]
enabled = false
ip = "http://130.240.114.44/api/"
user = "unicorn@ltu.se"
password = "INSERT-PASSWORD-HERE"

[phue]
enabled = false
ip = "130.240.114.98"

[discord]
enabled = false
url = "INSERT-URL-HERE"


# -------- EXPLANATIONS --------
#
# INPUT:
#
# Widefind: 1 is kitchen, 2 is livingroom, 3 is frontdoor
# Status: kitchen, livingroom, frontdoor, NOT-kitchen, NOT-livingroom, NOT-frontfoor
# Example: position_1_kitchen
#
# Fibaro: 31: microwave, 34: cupboard above dish stand, 37: cupboard above crane, 42: front door, 50: fridge, 55: cupboard left of crane, 58: ?, 63: cupboard above microwave
# Status: open, closed
# Example: door_42_open
#
# -----------------------------
#
# OUTPUT:
#
# Lamps: 2 is kitchen lamp, 3 is front door lamp, 4 is livingroom lamp
# Lamp actions: on, off, green, purple
# Example: lamp_3_on
#
# Discord: 0 is send
# Actions: send
# Example: discord_0_send (Specify message as argument)
#
# -----------------------------
#
# COMBINATION OF INPUT:
#
# Input can be combined to form more complex rules.
# The combinations can theoretically be infinite.
# Combined rules must follow this syntax (use "&"):
# Example: "door_42_open&widefind_2_frontdoor"


# -------- RULES --------

[rules_0]
inputName =         ["widefind_3_livingroom", "widefind_1_kitchen", "widefind_3_NOT-livingroom", "widefind_1_NOT-kitchen", "door_42_open", "door_42_closed"]
outputName =        ["lamp_4_disco",          "lamp_2_disco",       "lamp_4_off",                "lamp_2_off",             "lamp_3_disco", "lamp_3_off"    ]
outputFunction =    ["lamps",                 "lamps",              "lamps",                     "lamps",                  "lamps",        "lamps"         ]
outputArgument =    ["lamp_4_disco",          "lamp_2_disco",       "lamp_4_off",                "lamp_2_off",             "lamp_3_disco", "lamp_3_off"    ]

# LAMPS ON WHEN FRONT DOOR OPEN, OFF WHEN FRONT DOOR CLOSED
[rules_1]
inputName = ["door_42_open&widefind_2_frontdoor", "widefind_2_frontdoor", "door_42_open", "door_42_closed", "door_43_open", "door_42_closed"]
outputName = ["lamp_2_on", "lamp_2_off", "lamp_3_on", "lamp_3_off", "lamp_4_on", "lamp_4_off"]
outputFunction = ["lamps", "lamps", "lamps", "lamps", "lamps", "lamps"]
outputArgument = ["lamp_2_on&lamp_3_on", "lamp_2_off", "lamp_3_on", "lamp_3_off", "lamp_4_on", "lamp_4_off"]

# DISCORD TESTS
[rules_2]
inputName = ["door_42_open", "door_42_closed", "widefind_2_frontdoor", "widefind_2_NOT-frontdoor", "door_42_open&widefind_2_frontdoor"]
outputName = ["discord_0_send", "discord_0_send", "discord_0_send", "discord_0_send", "discord_0_send"]
outputFunction = ["discord", "discord", "discord", "discord", "discord"]
outputArgument = ["The front door has just been opened!", "The front door has just been closed!", "There is someone by the front door!", "Someone left the front door!", "Door opened and standing by front door!"]
