[userinfo]

user=0
activeRule="rules_2"

[simulator]

enabled=false

[rules_0]

inputName=[ "widefind_3_livingroom", "widefind_1_kitchen", "widefind_3_NOT-livingroom", "widefind_1_NOT-kitchen", "door_42_closed&widefind_3_livingroom", "door_42_closed" ]
outputName=[ "lamp_4_disco", "lamp_2_disco", "lamp_4_off", "lamp_2_off", "lamp_2_off", "lamp_3_off" ]
outputFunction=[ "lamps", "lamps", "lamps", "lamps", "lamps", "lamps" ]
outputArgument=[ "lamp_4_disco", "lamp_2_disco", "lamp_4_off", "lamp_2_off", "lamp_2_off", "lamp_3_off" ]

[rules_1]

inputName=[ "door_42_open", "door_42_closed", "door_42_open", "door_42_closed", "door_42_open", "door_42_closed" ]
outputName=[ "lamp_2_on", "lamp_2_off", "lamp_3_on", "lamp_3_off", "lamp_4_on", "lamp_4_off" ]
outputFunction=[ "lamps", "lamps", "lamps", "lamps", "lamps", "lamps" ]
outputArgument=[ "lamp_2_on", "lamp_2_off", "lamp_3_on", "lamp_3_off", "lamp_4_on", "lamp_4_off" ]

[rules_2]

inputName=[ "door_42_open", "door_42_closed" ]
outputName=[ "discord_0_send", "discord_0_send" ]
outputFunction=[ "discord", "discord" ]
outputArgument=[ "The front door has just been opened!", "The front door has just been closed!" ]

[rules_3_mat]

inputName=[ "widefind_1_livingroom", "widefind_3_livingroom" ]
outputName=[ "lamp_5_on", "lamp_3_on" ]
outputFunction=[ "lamps", "lamps" ]
outputArgument=[ "lamp_5_on", "lamp_3_on" ]

[rules_3_huvud]

inputName=[ "widefind_1_kitchen", "widefind_3_livingroom&widefind_3_NOT-livingroom", "widefind_3_livingroom&widefind_3_NOT-livingroom", "widefind_3_livingroom" ]
outputName=[ "lamp_3_on", "lamp_4_disco", "lamp_3_on", "lamp_2_on" ]
outputFunction=[ "lamps", "lamps", "lamps", "lamps" ]
outputArgument=[ "lamp_3_on", "lamp_4_disco", "lamp_3_on", "lamp_2_on" ]

[rules_3_huvud56]

inputName=[ "widefind_3_livingroom&door_42_open", "widefind_3_livingroom&door_42_open", "widefind_3_livingroom&widefind_1_kitchen&door_42_open" ]
outputName=[ "lamp_2_on", "lamp_3_on", "lamp_2_on" ]
outputFunction=[ "lamps", "lamps", "lamps" ]
outputArgument=[ "lamp_2_on", "lamp_3_on", "lamp_2_on" ]

[rules_3_huvud56NY]

inputName=[ "widefind_3_livingroom" ]
outputName=[ "lamp_4_disco" ]
outputFunction=[ "lamps" ]
outputArgument=[ "lamp_4_disco" ]

[rules_3_xomer]

inputName=[ "widefind_1_kitchen", "door_42_open", "door_42_open", "widefind_1_NOT-kitchen", "widefind_3_livingroom" ]
outputName=[ "discord_0_send", "discord_0_send", "lamp_4_blue", "lamp_4_disco", "lamp_2_on" ]
outputFunction=[ "discord", "discord", "lamps", "lamps", "lamps" ]
outputArgument=[ "Senece 1916 whit theere b", "up and down and all that i can see", "lamp_4_blue", "lamp_4_disco", "lamp_2_on" ]

[rules_3_Navi]

inputName=[ "widefind_3_livingroom" ]
outputName=[ "discord_0_send" ]
outputFunction=[ "discord" ]
outputArgument=[ "true to all the words we tell" ]

[rules_3_TEST_TEST]

inputName=[ "widefind_3_livingroom" ]
outputName=[ "lamp_4_off" ]
outputFunction=[ "lamps" ]
outputArgument=[ "lamp_4_off" ]
